### ISSUE TITLE
Please fix index.html

### ISSUE THREAD

**Issue by pavelvasev** [arirusso/d3-audio-spectrum#3]
Modern d3.js contains some utf characters, and your code causes syntax error. Please add following line to index.html

```
<meta http-equiv="content-type" content="text/html; charset=UTF8">
```

Details:
http://stackoverflow.com/questions/15237073/d3-js-uncaught-syntaxerror-unexpected-token-illegal

p.s. Web audio input seems to be broken, it doesn't work in chrome 45.0.2454.26 beta-m nor in canary. And I was not able to find `about:flags in the URL bar, and then enable Web Audio Input` flag.

**Comment by arirusso** [comment]
OK thank you, will get it fixed up as soon as I get a chance

Feel free to submit a pull request yourself in the meantime

**Comment by arirusso** [comment]
This should be fixed
